import Head from "next/head";
import React from "react";

const PageLayout = ({ children, title = "AppNext" }) => {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by JB" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>Eiii</header>
      {children}
    </div>
  );
};

export default PageLayout;
